'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class A3Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("A3Wrapper.SharedResources.A3Strings", GetType(A3Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert the program disc into the computer..
        '''</summary>
        Public Shared ReadOnly Property ERROR_INSERT_DISC() As String
            Get
                Return ResourceManager.GetString("ERROR_INSERT_DISC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid key..
        '''</summary>
        Public Shared ReadOnly Property ERROR_INVALID_KEY() As String
            Get
                Return ResourceManager.GetString("ERROR_INVALID_KEY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid key configuration settings..
        '''</summary>
        Public Shared ReadOnly Property ERROR_INVALID_KEY_CONFIGURATON() As String
            Get
                Return ResourceManager.GetString("ERROR_INVALID_KEY_CONFIGURATON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot read the license file..
        '''</summary>
        Public Shared ReadOnly Property ERROR_READ_LICENSE_ERROR() As String
            Get
                Return ResourceManager.GetString("ERROR_READ_LICENSE_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to write license file..
        '''</summary>
        Public Shared ReadOnly Property ERROR_WRITE_LICENSE_ERROR() As String
            Get
                Return ResourceManager.GetString("ERROR_WRITE_LICENSE_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entry not found in ZIP file..
        '''</summary>
        Public Shared ReadOnly Property ERROR_ZIP_ENTRY_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("ERROR_ZIP_ENTRY_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The program will now start..
        '''</summary>
        Public Shared ReadOnly Property INFO_PROGRAM_START() As String
            Get
                Return ResourceManager.GetString("INFO_PROGRAM_START", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Encrypted files were written to disc..
        '''</summary>
        Public Shared ReadOnly Property INFO_WRITTEN_ENCRYPTED_FILES_TO_DISK() As String
            Get
                Return ResourceManager.GetString("INFO_WRITTEN_ENCRYPTED_FILES_TO_DISK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Public Shared ReadOnly Property MSGBOX_TITLE_ERROR() As String
            Get
                Return ResourceManager.GetString("MSGBOX_TITLE_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information.
        '''</summary>
        Public Shared ReadOnly Property MSGBOX_TITLE_INFORMATION() As String
            Get
                Return ResourceManager.GetString("MSGBOX_TITLE_INFORMATION", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
